---
- name: web application deploy
  hosts: west
  remote_user: hank
  vars:
    workdir: /home/hank/code/src/github.com/aliencyborg/o-major-songs
  tasks:
    - name: ensure code/src/github.com/aliencyborg directory is present
      file:
        path: /home/hank/code/src/github.com/aliencyborg
        state: directory
      tags: [ prod, stage ]

    ## STAGE ##

    - name: clone or update o-major-songs repository (stage)
      git:
        accept_hostkey: yes
        dest: "{{ workdir }}"
        key_file: /home/hank/.ssh/id_rsa
        repo: 'git@github.com:aliencyborg/o-major-songs.git'
        update: yes
        version: stage
      tags: stage

    - name: build docker image (stage)
      docker_image:
        force_source: yes
        name: o-major-songs
        source: build
        tag: stage
        build:
          path: "{{ workdir }}"
          pull: no
      tags: stage

    - name: run docker container (stage)
      docker_container:
        expose: 80
        image: o-major-songs:stage
        name: o-major-songs-stage
        restart_policy: always
        state: started
        env:
          LETSENCRYPT_HOST: 'oms.aliencyb.org'
          PORT: '80'
          VIRTUAL_HOST: 'oms.aliencyb.org'
      tags: stage

    ## PRODUCTION ##

    - name: clone or update o-major-songs repository (prod)
      git:
        accept_hostkey: yes
        dest: "{{ workdir }}"
        key_file: /home/hank/.ssh/id_rsa
        repo: 'git@github.com:aliencyborg/o-major-songs.git'
        update: yes
        version: prod
      tags: prod

    - name: build docker image (prod)
      docker_image:
        force_source: yes
        name: o-major-songs
        source: build
        tag: prod
        build:
          path: "{{ workdir }}"
          pull: no
      tags: prod

    - name: run docker container (prod)
      docker_container:
        expose: 80
        image: o-major-songs:prod
        name: o-major-songs
        state: started
        env:
          LETSENCRYPT_HOST: 'omajorsongs.com,www.omajorsongs.com'
          PORT: '80'
          VIRTUAL_HOST: 'omajorsongs.com,www.omajorsongs.com'
      tags: prod
